---
title: "Project03"
author: "Marco Pinter"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's first manipulate our data 
```{r}

savant <- read.csv("savant_data.csv")

str(savant)

savant$game_date <- NULL
savant$on_1b<- NULL
savant$on_2b<- NULL
savant$on_3b <- NULL
savant$release_pos_x <- NULL
savant$release_pos_z <- NULL
savant$player_name <- NULL
savant$pitcher <- NULL
savant$batter <- NULL
savant$spin_dir <- NULL
savant$spin_rate_deprecated <- NULL
savant$break_angle_deprecated <- NULL
savant$break_length_deprecated <- NULL
savant$des <- NULL
savant$type <- NULL
savant$game_type <- NULL
savant$tfs_deprecated <- NULL
savant$tfs_zulu_deprecated <-  NULL
savant$umpire <-  NULL
savant$sv_id <-  NULL
savant$fielder_2 <- NULL
savant$game_pk <- NULL
savant$pitcher.1 <- NULL
savant$fielder_2 <- NULL
savant$fielder_2.1 <- NULL
savant$fielder_3 <- NULL
savant$fielder_4 <- NULL
savant$fielder_5 <- NULL
savant$fielder_6 <- NULL
savant$fielder_7 <- NULL
savant$fielder_8 <- NULL
savant$fielder_9 <- NULL

table(savant$release_pos_x)

savant$hc_x <- as.double(savant$hc_x)
savant$hc_y <- as.double(savant$hc_y)
savant$vx0 <- as.double(savant$vx0)
savant$vy0 <- as.double(savant$vy0)
savant$vz0 <- as.double(savant$vz0)
savant$pfx_x <- as.double(savant$pfx_x)
savant$pfx_z <- as.double(savant$pfx_z)
savant$plate_x <- as.double(savant$plate_x)
savant$plate_z <- as.double(savant$plate_z)
savant$ax <- as.double(savant$ax)
savant$ay <- as.double(savant$ay)
savant$az <- as.double(savant$az)
savant$hit_distance_sc <- as.double(savant$hit_distance_sc)
savant$effective_speed <- as.double(savant$effective_speed)
savant$release_spin_rate <- as.double(savant$release_spin_rate)
savant$release_extension <- as.double(savant$release_extension)
savant$release_speed <- as.double((savant$release_speed))
savant$release_pos_y <- as.double(savant$release_pos_y)


savant$homerun <- ifelse(savant$events == "home_run",1,0)

savant_model <- glm(homerun ~ pitch_type + release_speed + description + 
    zone + stand + p_throws + home_team + away_team + hit_location + 
    bb_type + balls + strikes + game_year + pfx_x + pfx_z + plate_x + 
    plate_z + outs_when_up + inning + inning_topbot + hc_x + 
    hc_y + vx0 + vy0 + vz0 + ax + ay + az + sz_top + sz_bot + 
    hit_distance_sc + launch_speed + launch_angle + effective_speed + 
    release_spin_rate + release_extension + release_pos_y + estimated_ba_using_speedangle + 
    estimated_woba_using_speedangle + woba_value + woba_denom + 
    babip_value + iso_value + launch_speed_angle + at_bat_number + 
    pitch_number + pitch_name + home_score + away_score + bat_score + 
    fld_score + post_away_score + post_home_score + post_bat_score + 
    post_fld_score + if_fielding_alignment + of_fielding_alignment, data = savant)

summary(savant_model)

savant_model_opt <- step(savant_model, direction = "backward")

summary(savant_model_opt)

```

